server:
  port: 8083

spring:
  application:
    name: SensorsValue

  main:
    banner-mode: off

  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/avtomatika?currentSchema=public
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true            # Показывать SQL-запросы в логах
    properties:
      hibernate:
        format_sql: true           # Красиво форматировать SQL в логах
        generate_statistics: true  # Подробная статистика по работе Hibernate
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG                      # Показывает сами SQL-запросы
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Показывает значения параметров запросов
    org.springframework.scheduling: DEBUG         # Планировщик задач (если используешь @Scheduled)
    org.springframework.context.annotation.AnnotationConfigApplicationContext: TRACE # Отлавливает кэширование

arduino:
  base: http://192.168.1.10

myapp:
  arduino:
    poll-interval-seconds: 1
  statistics:
    median-period-seconds: 10