server:
  port: 8081

spring:
  application:
    name: Prognoz

  main:
    banner-mode: off

  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/avtomatika?currentSchema=public
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  hikari:
    maximum-pool-size: 10
    minimum-idle: 3
    connection-timeout: 30000

logging:
  level:
    org.hibernate.SQL: DEBUG                      # Показывает сами SQL-запросы
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Показывает значения параметров запросов
    org.springframework.scheduling: DEBUG         # Планировщик задач (если используешь @Scheduled)

    org.springframework.context.annotation.AnnotationConfigApplicationContext: TRACE # Отлавливает кэширование
myapp:
  services:
    weather:
      url: https://api.openweathermap.org/
      api-key: 1e9d31abb8e72662aeed9d1e05496b08
      rain-threshold: 0.7            # Вероятность осадков